services:
  mysql-caelis:
    image: mysql:8.0
    container_name: mysql-caelis
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: caelis_user
      MYSQL_PASSWORD: caelis_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_caelis_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - caelis-network

  phpmyadmin-caelis:
    image: phpmyadmin:latest
    container_name: phpmyadmin-caelis
    restart: always
    environment:
      PMA_HOST: mysql-caelis
      PMA_PORT: 3306
    ports:
      - "8085:80"
    depends_on:
      - mysql-caelis
    networks:
      - caelis-network

volumes:
  mysql_caelis_data:

networks:
  caelis-network:
    driver: bridge